source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FirstJulianCocoaPod_Example', :exclusive => true do
  pod 'FirstJulianCocoaPod', :path => '../'
end

target 'FirstJulianCocoaPod_Tests', :exclusive => true do
  pod 'FirstJulianCocoaPod', :path => '../'

  
end
